services:
  discordbot:
    build: .
    container_name: DiscordBot
    restart: unless-stopped
    
    volumes:
      - ./Data/:/app/Data/

    networks:
      - lavalink
  
networks:
  lavalink:
    external: true
